name: Continuous Integration
on:
  pull_request:
    branches:
      - dev
    paths-ignore: 
      - '.github**'
      
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Install conan linux
        run: sudo pip install conan
      - name: checkout
        uses: actions/checkout@v2
      - name: Install conan dependencies
        run: |
          mkdir ./build
          cd ./build
          conan install .. --build=missing      
      - name: qmake
        run: |
         cd ./build
         qmake ../DesignYourNetwork.pro "CONFIG+=release"
      - name: make
        run: |
          cd ./build
          make qmake_all
          make
      - name: tests
        run: ./build/tests/tests
          
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Configure msvc cl.exe compiler
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install conan windows
        run: pip install conan
      - name: checkout
        uses: actions/checkout@v2
      - name: Install conan dependencies
        run: |
          mkdir ./build
          cd ./build
          conan install .. --build=missing      
      - name: qmake
        run: |
         cd ./build
         qmake ../DesignYourNetwork.pro "CONFIG+=release"
      - name: nmake
        run: |
          cd ./build
          nmake.exe qmake_all
          nmake.exe
      - name: tests
        run: ./build/tests/release/tests.exe
